---
# handlers file for docker
- name: docker_facts
  copy:
    content: >
      {
        "Version": "{{ version.stdout }}",
        "Build": "{{ build.stdout }}",
        "Date of creation": "{{ ansible_date_time.iso8601 }}"
      }
  dest: /etc/ansible/facts.d/docker.fact

